export default {
  root: {
    SplashScreen: "SplashScreen",
    WalletSetup: "WalletSetup",
    Terms: "Terms",
    PrivacyPolicy: "PrivacyPolicy",
    SendMoney: "SendMoney",
    HomeScreen: "HomeScreen",
    CreateMnemonic: "CreateMnemonic",
    CheckMnemonic: "CheckMnemonic",
    RecoverWallet: "RecoverWallet",
    AddressBook: "AddressBook",
    QRScanner: "QRScanner",
    QRGenerator: "QRGenerator",
    EditContact: "EditContact",
    Settings: "Settings",
    AboutApp: "AboutApp",
    CustomerSupport: "CustomerSupport",
    CaptionOutput: "CaptionOutput",
    BackupWallet: "BackupWallet",
    WalletCreated: "WalletCreated",
    WalletImported:"WalletImported",
    WalletInfo: "WalletInfo",
    AddWallet: "AddWallet",
    ReceiveMyQcCode: "ReceiveMyQcCode",
    ScanQR: "ScanQR",
    SendFTM: "SendFTM",
    SingleWallet: "SingleWallet",
    ValidatorNode: "ValidatorNode",
    StakingAmount: "StakingAmount",
    Success: "Success"
  },
  HomeScreen: {
    Home: "Home",
    Wallet: "Wallet",
    SendReceive: "SendReceive",
    Staking: "Staking",
    Settings: "Settings"
  }
};
